---
services:
  db: 
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example 

  adminer:
    image: adminer
    restart: always
    ports:
     - 9093:9000
     
  frontend:
    image: fronend-server
    ports:
     - 5000:5000
  cache:
    image: redis 
    restart: unless-stopped
    ports: 
    - 6379:6379


  backend:
    image: backend-server
    ports:
     - 8080:8080
    environment:
      REDIS_HOST: cache
      POSTGRES_HOST: db
      POSTGRES_USER: 
      POSTGRES_DATABASE: 
      POSTGRES_PASSWORD: example
version: "3.8"
