--- 
services: 
  adminer: 
    image: adminer
    ports: 
      - "9093:9000"
    restart: always
  backend: 
    depends_on: 
      - db
      - cache
    environment: 
      POSTGRES_DATABASE: ~
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: example
      POSTGRES_USER: ~
      REDIS_HOST: cache
    image: backend-with-user
  cache: 
    image: redis
    ports: 
      - "6379:6379"
    restart: unless-stopped
  db: 
    environment: 
      POSTGRES_PASSWORD: example
    image: "postgres:13.2-alpine"
    restart: unless-stopped
    volumes:
     - ./database:/var/lib/postgresql/data
  frontend:
    image: frontend-with-user
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - 80:80
    depends_on:
     - frontend
     - backend
        
version: "3.8"
